# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0002_auto_20171028_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default='2017-04-13'),
            preserve_default=False,
        ),
    ]
