# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0002_auto_20171223_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='test',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
