# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0003_auction_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
