# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0003_auction_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='test',
        ),
    ]
