# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0004_remove_auction_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
