# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0004_auto_20171029_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateField(),
        ),
    ]
