# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassapp', '0005_auto_20171029_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
